# Generated by Django 3.1.2 on 2020-10-25 07:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CKKItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50)),
                ('crawled_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('desc_text', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metaKeywords', models.TextField()),
                ('breadcrumbs', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('images', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
